// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef PROTOBUF_INCLUDED_messages_2eproto
#define PROTOBUF_INCLUDED_messages_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_messages_2eproto 

namespace protobuf_messages_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_messages_2eproto
namespace rpc {
class InputDevice;
class InputDeviceDefaultTypeInternal;
extern InputDeviceDefaultTypeInternal _InputDevice_default_instance_;
}  // namespace rpc
namespace google {
namespace protobuf {
template<> ::rpc::InputDevice* Arena::CreateMaybeMessage<::rpc::InputDevice>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace rpc {

// ===================================================================

class InputDevice : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpc.InputDevice) */ {
 public:
  InputDevice();
  virtual ~InputDevice();

  InputDevice(const InputDevice& from);

  inline InputDevice& operator=(const InputDevice& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputDevice(InputDevice&& from) noexcept
    : InputDevice() {
    *this = ::std::move(from);
  }

  inline InputDevice& operator=(InputDevice&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InputDevice& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputDevice* internal_default_instance() {
    return reinterpret_cast<const InputDevice*>(
               &_InputDevice_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InputDevice* other);
  friend void swap(InputDevice& a, InputDevice& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputDevice* New() const final {
    return CreateMaybeMessage<InputDevice>(NULL);
  }

  InputDevice* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputDevice>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputDevice& from);
  void MergeFrom(const InputDevice& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputDevice* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 vert = 1;
  void clear_vert();
  static const int kVertFieldNumber = 1;
  ::google::protobuf::int32 vert() const;
  void set_vert(::google::protobuf::int32 value);

  // int32 hori = 2;
  void clear_hori();
  static const int kHoriFieldNumber = 2;
  ::google::protobuf::int32 hori() const;
  void set_hori(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rpc.InputDevice)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 vert_;
  ::google::protobuf::int32 hori_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InputDevice

// int32 vert = 1;
inline void InputDevice::clear_vert() {
  vert_ = 0;
}
inline ::google::protobuf::int32 InputDevice::vert() const {
  // @@protoc_insertion_point(field_get:rpc.InputDevice.vert)
  return vert_;
}
inline void InputDevice::set_vert(::google::protobuf::int32 value) {
  
  vert_ = value;
  // @@protoc_insertion_point(field_set:rpc.InputDevice.vert)
}

// int32 hori = 2;
inline void InputDevice::clear_hori() {
  hori_ = 0;
}
inline ::google::protobuf::int32 InputDevice::hori() const {
  // @@protoc_insertion_point(field_get:rpc.InputDevice.hori)
  return hori_;
}
inline void InputDevice::set_hori(::google::protobuf::int32 value) {
  
  hori_ = value;
  // @@protoc_insertion_point(field_set:rpc.InputDevice.hori)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_messages_2eproto
